platform :ios, '9.0'

target 'DatePickerDemo' do
  use_frameworks!

  # Pods for DatePickerDemo
  pod 'BRPickerView'
  pod 'SnapKit'

  target 'DatePickerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatePickerDemoUITests' do
    # Pods for testing
  end

end
