# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GradientLayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GradientLayerDemo
  pod 'SnapKit'

  target 'GradientLayerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GradientLayerDemoUITests' do
    # Pods for testing
  end

end
