# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GCDDemo_EnterLeaveNotify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GCDDemo_EnterLeaveNotify
    pod 'Alamofire'

  target 'GCDDemo_EnterLeaveNotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GCDDemo_EnterLeaveNotifyUITests' do
    # Pods for testing
  end

end
