# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ShadowOffsetDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShadowOffsetDemo

  target 'ShadowOffsetDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapKit'

  end

  target 'ShadowOffsetDemoUITests' do
    # Pods for testing
  end

end
