platform :ios, ‘9.0’
use_frameworks!
inhibit_all_warnings!

target 'TerminalComDemo' do
    pod 'SnapKit'
    pod 'SwiftSocket'
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'Socket.IO-Client-Swift'
end





