# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WeexDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeexDemo
  pod 'SnapKit'
  pod 'WeexSDK', '0.28.0'
  pod 'WXDevtool'
  pod 'SDWebImage', '3.7.5'

end
